repos:
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args: [ "--check", "--diff", "--color"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [ "--show-source" ]
