F_TAIL = "tail"
F_REGISTRATION_NUMBER = "REGISTRATION_NUMBER"
F_MAINTENANCE_REVISION_NUMBER = "MAINTENANCE_REVISION_NUMBER"
F_PIPELINE = "pipeline"

# versioning
F_RUN_VERSION = "run_version"
F_PROCESSED_DATA_VERSION = "processed_data_version"
F_RAW_DATA_VERSION = "raw_data_version"
